steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/deliciousness-recipes",
        ".",
        "-f",
        "Dockerfile",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/deliciousness-recipes:latest"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - run
      - deploy
      - deliciousness-recipes
      - --image
      - gcr.io/$PROJECT_ID/deliciousness-recipes:latest
      - --region
      - us-central1
      - --platform
      - managed
      - --min-instances=0
      - --max-instances=1
      - --allow-unauthenticated
      - "--update-env-vars=REDEPLOY_ID=$BUILD_ID"

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - beta
      - run
      - domain-mappings
      - create
      - --service=deliciousness-recipes
      - --domain=recipes.brickapp.net
      - --region
      - us-central1
