// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package tokens

import (
	"time"
)

type Token struct {
	AccessToken  string
	RefreshToken string
	TokenType    string
	Expiry       time.Time
	ExpiresIn    int64
	Vendor       string
	CreatedAt    time.Time
	UserID       string
}
