// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package recipes

import (
	"time"
)

type Recipe struct {
	ID           int64
	Name         string
	Description  string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Ingredients  string
	Instructions string
	CookingTime  int64
	Image        string
}
