// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package recipes

import (
	"context"
	"time"
)

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO
    recipes (
        id,
        name,
        description,
        ingredients,
        instructions,
        cooking_time
    )
VALUES
    (?, ?, ?, ?, ?, ?) RETURNING id, name, description, created_at, updated_at, ingredients, instructions, cooking_time, image
`

type CreateRecipeParams struct {
	ID           int64
	Name         string
	Description  string
	Ingredients  string
	Instructions string
	CookingTime  int64
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (*Recipe, error) {
	row := q.db.QueryRowContext(ctx, createRecipe,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Ingredients,
		arg.Instructions,
		arg.CookingTime,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Ingredients,
		&i.Instructions,
		&i.CookingTime,
		&i.Image,
	)
	return &i, err
}

const deleteRecipe = `-- name: DeleteRecipe :exec
DELETE FROM recipes
WHERE
    id = ?
`

func (q *Queries) DeleteRecipe(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRecipe, id)
	return err
}

const getRecipe = `-- name: GetRecipe :one
SELECT
    id, name, description, created_at, updated_at, ingredients, instructions, cooking_time, image
FROM
    recipes
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetRecipe(ctx context.Context, id int64) (*Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipe, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Ingredients,
		&i.Instructions,
		&i.CookingTime,
		&i.Image,
	)
	return &i, err
}

const listRecipes = `-- name: ListRecipes :many
SELECT
    id, name, description, created_at, updated_at, ingredients, instructions, cooking_time, image
FROM
    recipes
ORDER BY
    created_at DESC
`

func (q *Queries) ListRecipes(ctx context.Context) ([]*Recipe, error) {
	rows, err := q.db.QueryContext(ctx, listRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Ingredients,
			&i.Instructions,
			&i.CookingTime,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecipe = `-- name: UpdateRecipe :exec
UPDATE recipes
SET
    name = ?,
    description = ?,
    updated_at = ?,
    ingredients = ?,
    instructions = ?,
    cooking_time = ?
WHERE
    id = ?
`

type UpdateRecipeParams struct {
	Name         string
	Description  string
	UpdatedAt    time.Time
	Ingredients  string
	Instructions string
	CookingTime  int64
	ID           int64
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) error {
	_, err := q.db.ExecContext(ctx, updateRecipe,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
		arg.Ingredients,
		arg.Instructions,
		arg.CookingTime,
		arg.ID,
	)
	return err
}
