// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package users

import (
	"time"
)

type User struct {
	ID         string
	Email      string
	Name       string
	GivenName  string
	FamilyName string
	Picture    string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
